### ISSUE TITLE
Include a fixed header bar  which scrolls to the appropriate section

### ISSUE THREAD

**Issue by tweettypography** [tweettypography/oktoberfesthmpf#1]
The site header should include a bar with links to each of the content sections of the site and should scroll to the appropriate section when the link is clicked.

**Comment by matadur** [comment]
Bar, links, anchored sections - complete. Remaining: smooth scroll to sections instead of jump.

**Comment by tweettypography** [comment]
We probably ought to use [scrollspy](http://getbootstrap.com/javascript/#scrollspy) to make sure the header keeps in sync, if we're not already.

**Comment by matadur** [comment]
scrollspy added.

**Comment by matadur** [comment]
Smooth scroll added.
