### ISSUE TITLE
Is the 6th section Food or Sponsors?

### ISSUE THREAD

**Issue by matadur** [tweettypography/oktoberfesthmpf#10]
The wireframe shows Sponsors; the icons created have a Food one instead.

**Comment by tweettypography** [comment]
Beer / food should be one section. Sponsors section should also be included.

**Comment by matadur** [comment]
Has the design changed? You've now removed Sponsors from the links.

**Comment by tweettypography** [comment]
I commented out the sections that we probably don't have content for prior to the initial launch
