### ISSUE TITLE
Header image shouldn't include text and logo

### ISSUE THREAD

**Issue by tweettypography** [tweettypography/oktoberfesthmpf#17]
We'll layer those in after after the fact

**Comment by thepkpnthr** [comment]
My bad... I've uploaded to dropbox the unedited image & an edited image (with R10-pixel gaussian blur).  I'll leave it to you guys to insert the icon & text.  Definitely consult with Lara on this as the branding's hers.

(Believe it or not my work computer's still running IE7 & IT won't give me another choice, so I can't mark this complete.)

**Comment by matadur** [comment]
Banner switched to new image.
