### ISSUE TITLE
Users should be able to easily understand what the event is and why they should attend

### ISSUE THREAD

**Issue by tweettypography** [tweettypography/oktoberfesthmpf#2]
A short description (1-3 paragraphs of text) should be written which can be used as part of the first section of the site to give people a feel for the event. This should be as concise and informative as possible. It will be possible to call out sections of this text with special emphasis as needed.

**Comment by tweettypography** [comment]
We have some simple text for this now, should we enhance it or is it acceptable as-is?

**Comment by thepkpnthr** [comment]
Looks good to me!  Only 1 change in the final phrase -- change to: "all
proceeds go towards _the_ park endowment".  Unless it's not for this park,
in which case, perhaps we can be more general? ("... the neighborhood
endowment", "...the neighborhood development fund", etc)

~Ryan
