### ISSUE TITLE
Find different background image for Tickets section

### ISSUE THREAD

**Issue by matadur** [tweettypography/oktoberfesthmpf#22]

**Comment by thepkpnthr** [comment]
Uploaded picture for "Tickets" section....

To clarify, each section photo is:
_Tickets - picture of bottle caps... if you hate that, consider using the
food truck or kegs ones instead_
Home - "header" image
Beer & Food - picture of Fountain Square brewing glasses
Bands - picture of back of guy playing guitar
Map - picture of bikes
Swag (when it's added to order Oktoberfest gear) - picture of t-shirts

**Comment by tweettypography** [comment]
Swapped in a different picture for tickets. We can update again if needed.
