### ISSUE TITLE
Full-screen arrow icon in white for green map

### ISSUE THREAD

**Issue by matadur** [tweettypography/oktoberfesthmpf#24]
Something that is highly visible on new green map

**Comment by matadur** [comment]
Also add one with drop shadow etc for on-hover

**Comment by thepkpnthr** [comment]
Added 3 icons:

4arrow_transparent: for adding on top of green background
4arrow_white: for rollover (i prefer this option)
4arrow_white_dropshadow: other option for rollover

**Comment by matadur** [comment]
Added icon & hover to the map
