### ISSUE TITLE
Should we use Bootstrap 3.0 instead of 2.3.2?

### ISSUE THREAD

**Issue by matadur** [tweettypography/oktoberfesthmpf#8]
Bootstrap is in RC1 of v3.0. Should we stick with the stable 2.3.2 or switch to 3.0 before we get too deep?

**Comment by tweettypography** [comment]
I could go either way. If you'd like to get the repo upgraded to 3.0 I'm all for it.

**Comment by tweettypography** [comment]
Probably needs additional work, but I took a first stab at upgrading to Bootstrap 3.0. Also switching to the Bootstrap LESS files (gives us the ability to leverage the library of mix-ins in our own LESS).

**Comment by matadur** [comment]
Cool. This threw all the current styles askew; I'll work on updating.

**Comment by matadur** [comment]
Styles fixed.
